apiVersion: v1
kind: Pod
metadata:
  name: selector-pod
spec:
  containers:
      - name: myselect-con1
        image: httpd
        ports:
          - containerPort: 80
  nodeSelector:
     env: dev
    
