apiVersion: v1
kind: Pod
metadata: 
  name: sec-configpod
spec:
  containers:
    - name: env-con-sec
      image: nginx
      env:
        - name: DB_username
          valueFrom:
             secretKeyRef:
               name: prod-secret
               key:  username
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: prod-secret
              key: password
