apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu-pod
spec:
  tolerations:
    - key: env
      operator: "Equal"
      value: "test"
      effect: "NoExecute"
  containers:
     - name: my-container
       image: ubuntu
       command: ['bash', '-c','echo Hello && sleep 3600']
